ios/RNAppleAuthentication/RNAppleAuthButtonViewManager.m

https://github.com/invertase/react-native-apple-authentication/issues/30 
- rename class name `RNAppleAuthButtonViewManagerWhiteOutlineSignUp` at L125.
- remove `__IPHONE_OS_VERSION_MAX_ALLOWED`, add `if(@available(iOS 13.2, *))`
- `__IPHONE_OS_VERSION_MAX_ALLOWED` may not work for the minor version.
- e.g. at iOS 13.2.3 simulator, __IPHONE_OS_VERSION_MAX_ALLOWED is __IPHONE_13_0
- when set SignUp, if iOS13.2+ then display SignUp else Default (SignIn)

fix SignUp and WhiteOutline button

---

README.md

I've noticed that there's a lot of question regarding why "email" and "full name" returns null, even on the other repositories regarding apple authentication.
I've added a guide on how to be able to retrieve the "email" and "full name" again.

docs: added FAQs section

---

lib/index.d.ts

It's helpful to export this additional type for projects that have strict type-checking enabled.
For instance this usage:
```js
import appleAuth from from "@invertase/react-native-apple-authentication";
function logout() {
appleAuth
.performRequest({
user,
requestedOperation: AppleAuthRequestOperation.LOGOUT,
})
.then((response) => { // error: no explicit type
console.log({ response });
})
}
```
results in a typescript error in the `then` block, as we don't have a way to type the function parameter `response` without constructing it from scratch or copy/pasting from this project.

feat(typescript): export AppleAuthRequestResponse type

---

README.md

The default example won't render the button as there are no default styles with a width and a height applied.

Add width+height in style for button on example so it renders

---

ios/RNAppleAuthentication/RNAppleAuthUtils.h

Compiler error: `NSObject` is not defined. I think the reason is because of the missing import Foundation.

fix(ios): add missing import

---

README.md
docs/interfaces/_lib_index_d_.rnappleauth.module.md

As seen in #9 and #89, the function `getCredentialStateForUser` can trigger an error on simulator, this is a normal behaviour as this function is only working on real device.
Just a small PR to specify it in the documentation

Update documentation for getCredentialStateForUser

---

lib/AppleAuthModule.js

Currently, the method `performRequest` should allow to receive the `state` as a param but now is showing the next Error:
This is because `state` need to be added in the request `performRequest(...)`:
Fix:
```javascript
const { requestedScopes, requestedOperation, user, nonce, state, nonceEnabled, ...rest } = requestOptions;
```
@mikehardy @Salakar

Fix 'Invalid params found...state'

---

package.json
yarn.lock

Obsoletes #100  which was hung up on CLA somehow
Also works in an updated 'np' which includes PRs I worked through with the author in it's transitive dependency chain to shed an unpatched vulnerability
https://snyk.io/vuln/SNYK-JS-URLREGEX-569472
https://github.com/sindresorhus/npm-name/pull/40
https://github.com/sindresorhus/np/pull/545

chore: yarn upgrade --latest / moved np to devDepenencies

---

README.md

Adding a missing instruction since `react-native run-ios` failed to build without doing `pod install`.

Add missing installation instruction

---

README.md
android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java
docs/interfaces/_lib_index_d_.appleauthandroid.md
example/android/app/build.gradle
example/app.android.js
lib/index.d.ts
lib/index.js
type-test.tsx

In further testing I determined that the Sign In with Apple process requires Android 4.4 (API 19) or higher, when Android [switched to the chromium engine](https://developer.android.com/guide/webapps/migrating). In fact, you can't even access your [Apple ID](https://appleid.apple.com/) page in the browser pre 4.4. So to keep consistent with the Apple side of this module, I added an `isSupported` check to `appleAuthAndroid` that returns true for API 19+. The library still builds on API 16.
I also excluded `okhttp` from `flipper-network-plugin` in the example app — [a change](https://github.com/facebook/react-native/pull/29260) that is making its way into the main repo.

Implemented isSupported check for Android

---

RNAppleAuthentication.podspec

This is apparently needed for Xcode 12 compatibility
Reference: https://github.com/facebook/react-native/issues/29633

fix(ios): depend on React-Core directly, not React

---

android/src/main/java/com/RNAppleAuthentication/webview/SignInWebViewDialogFragment.kt

This change fixes a compilation error when targeting API30 by treating the webview dialog context as non-null to satisfy the type system. Since the context is accessed inside the fragment's `onCreateView` callback, it should always be non-null anyway.

Fix API30 compilation error

---

README.md

"Implement the logout process" section keeps the old operation constants usage from "v1.x" that is `AppleAuthRequestOperation`. I updated it with the new usage that is `appleAuth.Operation`.

"Implement the logout process" section details updated with new usage

---

README.md

Add missing appleAuthAndroid import in README.md
```bash
import React from 'react';
import { View } from 'react-native';
import { AppleButton } from '@invertase/react-native-apple-authentication';  //appleAuthAndroid is missing in the import
async function onAppleButtonPress() {
}
// Apple authentication requires API 19+, so we check before showing the login button
function App() {
return (
<View>
{appleAuthAndroid.isSupported && (
<AppleButton
buttonStyle={AppleButton.Style.WHITE}
buttonType={AppleButton.Type.SIGN_IN}
onPress={() => onAppleButtonPress()}
/>
)}
</View>
);
}```

Add missing appleAuthAndroid import in README.md

---

docs/FIREBASE.md
docs/MIGRATION.md

While migrating to v2, I didn't see any of the docs mention migrating from `AppleAuthError` to `appleAuth.Error`. This PR attempts to rectify that for anybody else who runs across this in the future.

Update Error handling documentation for v2

---

README.md

I was able to implement @kidmysoul 's JWT parser reference from [this issue comment](https://github.com/invertase/react-native-apple-authentication/issues/160#issuecomment-735342187) to get the email on subsequent login attempts, so this is a small block of code to help others who might want to do the same.

update README with info on parsing identity token

---

lib/AppleButton.android.js

Per discussions on [ReferenceError: ReferenceError: Can't find variable: AppleButton #150 ](https://github.com/invertase/react-native-apple-authentication/issues/150) it seems that use of the arrow function is problematic based on configurations with babel, potentially among other factors.
Changing this from using an arrow function fixes the issue and seems to be a stable fix.

fix(android): use function vs arrow for babel compat in AppleButton export

---

android/src/main/java/com/RNAppleAuthentication/webview/SignInWebViewDialogFragment.kt

related to: #178
@mikehardy Newest version of Android Gradle build linter are suggesting the change from `context!!` to `requireContext()`. This simple change fixes the lint errors. It's also recommended as your found out[ in this post](https://bentrengrove.com/blog/2020/6/15/requirecontext-or-context)

fix: Updates to recommended way of importing context

---

android/build.gradle
android/gradle.properties
example/android/build.gradle

Since Android Gradle Plugin 3.1 (2018), it's no longer required to specify buildToolsVersion for Android.

chore: remove buildToolsVersion

---

docs/ANDROID_EXTRA.md

URL was invalid in ANDROID_EXTRA docs. I replaced it with new one.

docs: Fix URL for apple configuration in docs

---

docs/Auth0.md

Refer to FAQ where order of scopes matters. https://github.com/invertase/react-native-apple-authentication#faqs

fix: Reorder requested scopes to place FULL_NAME first

---

android/build.gradle

Change is required as per announce in community: https://github.com/react-native-community/discussions-and-proposals/issues/671
Fixes #328

fix(android): declare namespace / buildconfig options for gradle plugin 8+ compatibility

---

README.md

If using this library inside an Expo project, appleAuthAndroid is an empty object until Expo prebuild has been ran

docs: Update README.md with note about Expo prebuild

---

README.md

Currently you need to add one line of configuration to enable Apple Sign-in with Expo project. This does exactly that.

docs: Add steps to enable Apple Sign-in with Expo

---

RNAppleAuthentication.podspec
ios/RNAppleAuthentication/RNAppleAuthASAuthorizationDelegates.m

I have been doing some work with this repo https://github.com/callstack/react-native-visionos
And wanted to contribute sharing what made it work for me following the instructions in [this post](https://www.oskarkwasniewski.dev/blog/bringing-react-native-libraries-to-apple-vision-pro#migrating-libraries)
This allows to run appleAuth methods for react-native-visionos
Fixes #350

feat: support for VisionOS

---

android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java

Fixes #362 (except for `responseType`, which is left out as explained [here](https://github.com/invertase/react-native-apple-authentication/issues/362#issuecomment-2776387504))

fix(android): pass the specified scope when creating configuration
